### ISSUE TITLE
you said you were not going to be working on custom servers

### ISSUE THREAD

**Issue by Dood9123** [themaoci/Enut#2]
i am now sad

**Comment by themaoci** [comment]
if it will be less retarder coded i will propably made an online version but as i say its useless work there
* i made customs to work but no boss spawns like its hardcoded in engine ...

**Comment by Dood9123** [comment]
so you're saying i can host a custom's private server right now?!?

**Comment by themaoci** [comment]
you will need to rewrite whole backend of the server like matchmaking/playerlist/and other things which isnt easy without any pattern how its done in backend

**Comment by Dood9123** [comment]
is there any way to port forward offline matches as they just host a local server?

**Comment by panicco** [comment]
No. When playing in offline mode your not connecting to a server. The emulation taking place currently in emutarkov is login emulation, inventory emulation, trader emulation. 

So all the required code for match making, tracking, stats/experience, player sync etc. Is not out there and will prove to be very difficult to re write.

**Comment by themaoci** [comment]
i will close that ;)
