### ISSUE TITLE
Boss Bots- No Gear

### ISSUE THREAD

**Issue by panicco** [themaoci/Enut#4]
Hello,
I have been working to help out with populating areas with correct bots and adding in laboratory scavs.
While using the code to find my way for bigmap(customs) I fixed your error for scavs but discovered a new issue.

Boss bots spawn's - stands still
No gear
no escorts spawn
This occurs on both bigmap and laboratory

I will submit my fix for customs spawn and boss vars and hopefully find a solution to no gear no escort

**Comment by themaoci** [comment]
you need to check if Equipment hash ID is equal to some parentID hashes ;)
propably i know whats happen there is too small ammount of bots added will update it at home with ur changes and push to git - they should work then normally (try easy difficulty because bots are made there only for easy)

**Comment by panicco** [comment]
Ok ill do some digging around. This happens with both bigmap and laboratory I take a look at the hashes aswell but if you get to it before me ill take a look through the fixes.

**Comment by panicco** [comment]
I took a Quick look and noticed some possible issues. with the bots:
All Id's are matching for bots.
If you look at the first ID hash tag youll notice that all bots we have made have the same id hashes.
same with parent id.
I also noticed that in my labs bots the 6 entries for parent id are not generated correctly.

Could this be an issue with the bot creation tool.?

I believe it should generate random id hashes and parent hashes. It looks like the bot tool is using the character id tags and not generating a new unique one.
I could be wrong but I would think that if:
4 bots with matching id tags would cause this issue.

If you look at some of the bots in the fist part of bigmap they do not have matching tags.
I will investigate more.

**Comment by panicco** [comment]
I have mostly solved this issue,
Header id's need to be unique to each bot.
I still need to investigate 2nd primary weapon. and Pistol slots.

I have rewritten the bot creation code to include randomization but im sure it can be better.
I will post what I have when I have finished with a few more primary headers

but Boss bots spawning with correct gear!!! Issue Solved
